### ISSUE TITLE
Model is not initialised on Testing

### ISSUE THREAD

**Issue by suhailpcv** [xamantra/momentum#29] opened 2020-07-31 10:02 UTC
Here are some example of my controllers,
```
  PreloadController()..config(lazy: false),
  ProfileController(),
```
![Screenshot 2020-07-31 at 6 02 14 PM](https://user-images.githubusercontent.com/60662024/89024633-fdafe500-d357-11ea-98b1-51c268a8cfb2.png)
.
But on the testing documentation, it seems that the model should've been initialised.

**Comment by xamantra** [comment] 2020-07-31 10:37
This is strange. It works fine on my test here.

Can you show me the contents of `mySewaApp()` and `PreloadController`'s `init()` implementation? Are you returning a model instance in that `init()` method?

**Comment by suhailpcv** [comment] 2020-07-31 10:43
@xamantra 
```
Momentum mySewaApp() {
  return Momentum(
    appLoader: PreloadSplash(),
    child: MySewaApp(),
    controllers: appControllers,
    services: appServices,
    persistSave: (context, key, value) async {
      var sharedPref = await StorageService.getByContext(context);
      var result = await sharedPref.setString(key, value);
      return result;
    },
    persistGet: (context, key) async {
      var sharedPref = await StorageService.getByContext(context);
      var result = sharedPref.getString(key);
      return result;
    },
  );
}
```
this is the init implementation
```
  @override
  PreloadModel init() {
    return PreloadModel(
      this,
      isJwtExpired: true,
      isRefreshExpired: true,
      isTenant: true,
      isRegistered: false,
      isSkipped: false,
      jwtToken: "",
      refreshToken: "",
      initialPage: PreloadEventAction.FirstTime,
    );
  }
```

**Comment by xamantra** [comment] 2020-07-31 10:45
@suhailpcv 
Can you see if this is null too?

![image](https://user-images.githubusercontent.com/37391380/89027852-d78d4380-d35d-11ea-9701-41485ead5887.png)

If `_currentActiveModel` is not null then you're doing good. You can call `model` in your testing directly.

**Comment by suhailpcv** [comment] 2020-07-31 10:47
@xamantra 
Unfortunately it is null :( I also tried debugging on the attributes of the model. it is null. weird
![Screenshot 2020-07-31 at 6 46 01 PM](https://user-images.githubusercontent.com/60662024/89028019-1f13cf80-d35e-11ea-9c2c-d040ca32b00b.png)

**Comment by xamantra** [comment] 2020-07-31 11:12
Can you try adding `duration` in your `pumpAndSettle()` call?

like
```dart
await tester.pumpAndSettle(Duration(milliseconds: 3000)); // 3 seconds
```

**Comment by suhailpcv** [comment] 2020-07-31 12:30
erm. I tried adding 3 seconds duration then I tried 10. still not working

**Comment by xamantra** [comment] 2020-07-31 13:35
I want to ask you if you can convert these two into a method that returns a list.

![image](https://user-images.githubusercontent.com/37391380/89039694-18dd1d80-d375-11ea-87b5-7eefe6f1fae8.png)

I'm assuming `appControllers` is a global variable same with `appServices`. The thing is during testing their state will also be global. Turning them into method that returns a list of controllers and services will create new instance every test and not share state between states.

Something like this:
```dart
List<MomentumController> appControllers() {
  return [ ... ];
}
```

**Comment by suhailpcv** [comment] 2020-07-31 15:45
@xamantra hey sorry for the late reply.
I tried changing them as you mentioned
```
Momentum mySewaApp() {
  return Momentum(
    appLoader: PreloadSplash(),
    child: MySewaApp(),
    controllers: appControllers(),
    services: appServices(),
    persistSave: (context, key, value) async {
      var sharedPref = await StorageService.getByContext(context);
      var result = await sharedPref.setString(key, value);
      return result;
    },
    persistGet: (context, key) async {
      var sharedPref = await StorageService.getByContext(context);
      var result = sharedPref.getString(key);
      return result;
    },
  );
}
```
The model is still null unfortunately
![Screenshot 2020-07-31 at 6 46 01 PM](https://user-images.githubusercontent.com/60662024/89052160-e0930a80-d387-11ea-967f-f3ec9224e855.png)

**Comment by xamantra** [comment] 2020-07-31 22:03
Are you using the latest version of the library?

**Comment by xamantra** [comment] 2020-07-31 22:20
If it doesn't work... Can you also try this:

https://github.com/flutter/flutter/issues/5728#issuecomment-431952063

![image](https://user-images.githubusercontent.com/37391380/89081903-0ee00c80-d3bf-11ea-8706-3cfb014f8033.png)

**Comment by suhailpcv** [comment] 2020-08-01 02:49
Yes I am using the 1.3.1 version. This is so weird dudeee
![Screenshot 2020-08-01 at 10 49 01 AM](https://user-images.githubusercontent.com/60662024/89092474-a2780400-d3e4-11ea-968b-23b99fe6cd50.png)

**Comment by xamantra** [comment] 2020-08-01 05:48
Another question, does your app works fine if you run it on device or emulator? Does this happen only during tests?

**Comment by suhailpcv** [comment] 2020-08-01 06:50
@xamantra yep everything is working fine. I skipped the unit test part during the early development phase, but now when it almost complete I feel like it doesn't feel complete without running any unit tests so here I am haha

**Comment by xamantra** [comment] 2020-08-01 07:03
![image](https://user-images.githubusercontent.com/37391380/89096256-e6c8cb80-d407-11ea-8ba2-1ce8c0db19e6.png)

Can you show the the contents of `appControllers()` method?

**Comment by suhailpcv** [comment] 2020-08-01 07:04
@xamantra 
```
List<MomentumController<dynamic>> appControllers() {
  return [
    PreloadController()..config(lazy: false),
    ProfileController(),
    ThemeController(),
    VerifyPhoneController(),
    VerifyOtpController(),
    AuthRegisterController(),
    HomeController(),
    NewListingController(),
  ];
}
```

**Comment by xamantra** [comment] 2020-08-01 07:07
there's nothing wrong. this is really weird. let me give you some more time for this. maybe I'll try to create a separate testing framework for this. because currently controller initialization is depending on widgets and flutter widget is flaky during testing...

**Comment by xamantra** [comment] 2020-08-01 07:09
btw, is there no error logs in the console during your test? if possible can you send an entire log here? if it is too long, you can paste the log in pastebin or something and link it here.

**Comment by suhailpcv** [comment] 2020-08-01 07:10
thanks a lot @xamantra , great work on the library tho I really love it!

**Comment by suhailpcv** [comment] 2020-08-01 07:14
there is no error if I remove the expect for the model values. however if I run it on debug. this is the log on the debug console. however this is just a warning right?
```
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.

Connecting to VM Service at http://127.0.0.1:52890/jw8NhGuX0cI=/ws
```

**Comment by xamantra** [comment] 2020-08-01 07:31
that log is all only related to dart.

I think I'll go make testing framework for this. Because currently too, even if you only want to test the controller (unit test), you need `testWidgets(...)` instead of just `test(...)`. testWidgets is very flaky, especially for asynchronous code.

**Comment by xamantra** [comment] 2020-08-01 07:33
Also even if we can't currently fix this, do not close the issue yet.

**Comment by suhailpcv** [comment] 2020-08-01 09:44
Okay that's great! I'm sure people would love a testing framework as well since there's not much coverage on testing for momentum in the community. Thanks a lot @xamantra !

**Comment by exts** [comment] 2020-08-02 17:41
Yeah this is an issue for me as well.

It can't even find the MyApp. Going to try reproducing in a standalone project to see if there's some weirdness going on (and this is w/ 1.3.2 dev build as well)

```
  testWidgets("index screen is found", (tester) async {
    await tester.runAsync(() async { //tried it with and without this as well
      var app = application();
      await tester.pumpWidget(app);

      var myapp = find.byType(MyApp); //myapp
      expect(myapp, findsOneWidget);
    });
  });
```

pumpAndSettle times out consistently so I stopped using it.

```dart
class _MyAppState extends MomentumState<MyApp> {
  SettingsController settingsController;

  @override
  void initMomentumState() {
    super.initMomentumState();
    settingsController = Momentum.controller<SettingsController>(context);
  }

  @override
  Widget build(BuildContext context) {
    var theme = settingsController.themeData();
    return MomentumBuilder(
      controllers: [],
      builder: (context, snapshot) {
        return MaterialApp(
          title: 'Week In Review',
          theme: ThemeData.dark().copyWith(
            primaryColor: theme.primaryColor,
            accentColor: theme.accentColor,
            textSelectionColor: theme.textSelectionColor,
            textSelectionHandleColor: theme.textSelectionHandleColor,
            buttonTheme: ButtonThemeData(
              buttonColor: theme.buttonColor,
            ),
            floatingActionButtonTheme: FloatingActionButtonThemeData(
              foregroundColor: theme.floatingActionButtonForeground,
              backgroundColor: theme.floatingActionButtonBackground,
            ),
            inputDecorationTheme: InputDecorationTheme(
              border: OutlineInputBorder(
                borderSide: BorderSide(
                  color: theme.inputBorderColor,
                ),
              ),
              focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(
                  color: theme.inputBorderFocusColor,
                ),
              ),
            ),
            iconTheme: IconThemeData(
              color: theme.iconColor,
            ),
          ),
          home: IndexScreen(),
        );
      },
    );
  }
}
```

Maybe this will help you find out the actual issue.

**Comment by xamantra** [comment] 2020-08-03 01:03
Yeah @exts, you get the `pumpAndSettle` timeout because of asynchronous code. Flutter should really fully support async code in test soon. But for now I'll be making a test framework for momentum controllers and model.

**Comment by exts** [comment] 2020-08-03 01:07
I'll test it the moment you post it here 👍

**Comment by exts** [comment] 2020-08-24 20:56
@xamantra are you still working on this one

**Comment by xamantra** [comment] 2020-08-25 23:35
Yeah, I'm still working on this. been busy lately. I already completed making `MomentumTester` but then I changed the API design so make it more simple and allow reusing of `Momentum` instance. Still need to add docs for it.

**Comment by xamantra** [comment] 2020-08-28 12:37
`MomentumTester` is now ready on `dev-1.3.2` branch. You can use this new feature by using the git repo in `pubspec.yaml`

```yaml
dependencies:
  # other packages ...
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: dev-1.3.2
  # other packages ...
```

#### Full documentation for `MomentumTester` [is here](https://xamdev.gq/momentum/#/momentum-tester).

### Example
```dart
  test('Momentum Tester Tool: Counter', () async {
    // create tester instance.
    var tester = MomentumTester(momentum());

    await tester.init(); // initialize the tester (calls bootstrap methods)

    var counter = tester.controller<CounterController>();
    expect(counter != null, true);
    expect(counter, isInstanceOf<CounterController>());
    expect(counter.model.value, 0);
    counter.increment();
    expect(counter.model.value, 1);
  });
```

Hey @suhailpcv and @exts sorry for the very slow development. Been so busy and now I manage to find free time to get back on this. If possible and you're still interested, I'd like to hear your feedback from this update.

**Comment by exts** [comment] 2020-08-28 14:07
Cool, and it's np. I will be testing this today/tonight and report back any issues I have.

**Comment by xamantra** [comment] 2020-08-28 19:29
There's no widget related function in this update. It is only for testing controllers, models and services. If you want to test your widgets you need to use the built in flutter widget testing functions.

**Comment by exts** [comment] 2020-08-31 02:28
@xamantra can you export MomentumTester, i had to import base. Also can you make it easy to expose momentum so we can send it to pumpWidget for testing widgets using the flutter api after we set up bootstrap, etc..

**Comment by xamantra** [comment] 2020-08-31 05:59
I think that might be possible. as for exporting `MomentumTester` I didn't notice that. Will fix in a minute.

**Comment by xamantra** [comment] 2020-08-31 06:05
I pushed on `dev-13.2` branch. I'll try to look into exposing `Momentum` instance after bootstrap for use in widget testing.

**Comment by exts** [comment] 2020-08-31 13:40
I mean if you can you could just create a simple method `getMomentum()` or `momentum()` and send us `_momentum` back.

**Comment by suhailpcv** [comment] 2020-09-13 05:56
@xamantra hey xamantra! sorry for the late update, it's working as expected now! The currentActiveModel is not null anymore.

**Closed** 2020-10-13 05:01 UTC
Labels: Published
